[package]
name = "arc-store-types"
version = "0.1.0-beta.6"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Foundational store types for arc"

[features]
default = ["std"]
std = [
	"dep:anyhow",
	"dep:directories",
	"dep:serde_json",
	"dep:bincode",
	"dep:rand_core",
	"serde/std",
	"blake3/std",
]

[dependencies]
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
rand_core = { version = "0.6.4", features = ["getrandom"], optional = true }
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"] }
anyhow = { version = "1.0.102", optional = true }
directories = { version = "6.0.0", optional = true }
serde_json = { version = "1.0.149", optional = true }
bincode = { version = "1.3.2", optional = true }
blake3 = { version = "1.8.4", default-features = false }

[dev-dependencies]
tempfile = "3.27.0"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2.17", features = ["js"] }
