//! State machine for pending AI-generated changes — the "Ghost Node" layer.
//!
//! When `arc ai resolve` or `arc generate` produces AI-authored content, the
//! result is staged here rather than written directly to the CAS.  A human
//! must run `arc ai approve` to cryptographically sign and commit the change,
//! enforcing the `Author::AI { human_sponsor }` dual-attestation model.
//!
//! The pending state is persisted to `.arc/ai/pending.json`.  The mutual
//! exclusion invariant (only one pending AI change at a time) is enforced by:
//!
//! - `arc snap` bails if `pending.json` exists (State Lock).
//! - `arc ai resolve` / `arc generate` bail if `pending.json` already exists.
//! - `arc ai approve` removes `pending.json` after committing.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::Result;
use arc_algebra_types::{Atom, Blake3Hash};
use serde::{Deserialize, Serialize};

// ── PendingKind ───────────────────────────────────────────────────────────────

/// Discriminates the source of a pending AI change.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PendingKind {
    /// Generated by `arc generate`.
    Generate,
    /// Produced by `arc ai resolve`.
    Resolve,
}

// ── PendingAiChange ───────────────────────────────────────────────────────────

/// A pending AI-authored change awaiting human cryptographic approval.
///
/// For `kind = Resolve`, [`staged_atoms`] and [`staged_deps`] hold the
/// pre-resolved merge geometry (blobs already written to CAS) so that
/// `arc ai approve` only needs to construct a `Change` and update the view.
///
/// For `kind = Generate`, [`staged_atoms`] / [`staged_deps`] are empty; the
/// approve path calls `snap_ai()` to diff the working directory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingAiChange {
    /// Whether this was produced by `arc generate` or `arc ai resolve`.
    pub kind: PendingKind,
    /// AI model identifier (e.g. `"gpt-4o-mini"`).
    pub model: String,
    /// Unix timestamp (seconds since epoch) when the pending change was created.
    pub timestamp: u64,
    /// Combined semantic intent / goal describing the proposed change.
    pub intent: String,
    /// Working-directory files that were written by the AI (relative paths).
    pub affected_files: Vec<PathBuf>,
    /// Pre-resolved atoms for the Resolve case (blobs already written to CAS).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub staged_atoms: Vec<Atom>,
    /// Merge dependencies for the Resolve case.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub staged_deps: Vec<Blake3Hash>,
}

impl PendingAiChange {
    /// Create a new Generate-kind pending change with the current timestamp.
    pub fn new_generate(model: String, intent: String, affected_files: Vec<PathBuf>) -> Self {
        Self {
            kind: PendingKind::Generate,
            model,
            timestamp: unix_now(),
            intent,
            affected_files,
            staged_atoms: Vec::new(),
            staged_deps: Vec::new(),
        }
    }

    /// Create a new Resolve-kind pending change with pre-staged atoms and deps.
    pub fn new_resolve(
        model: String,
        intent: String,
        affected_files: Vec<PathBuf>,
        staged_atoms: Vec<Atom>,
        staged_deps: Vec<Blake3Hash>,
    ) -> Self {
        Self {
            kind: PendingKind::Resolve,
            model,
            timestamp: unix_now(),
            intent,
            affected_files,
            staged_atoms,
            staged_deps,
        }
    }
}

fn unix_now() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

// ── Persistence helpers ───────────────────────────────────────────────────────

/// Path: `<repo_root>/.arc/ai/pending.json`.
fn pending_path(repo_root: &Path) -> PathBuf {
    repo_root.join(".arc").join("ai").join("pending.json")
}

/// Persist `pending` to `<repo_root>/.arc/ai/pending.json`.
pub fn save_pending_ai(repo_root: &Path, pending: &PendingAiChange) -> Result<()> {
    let path = pending_path(repo_root);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(pending)?;
    std::fs::write(&path, json)?;
    Ok(())
}

/// Load the pending AI change from `<repo_root>/.arc/ai/pending.json`.
///
/// Returns `None` if the file does not exist or cannot be parsed.
pub fn load_pending_ai(repo_root: &Path) -> Option<PendingAiChange> {
    let bytes = std::fs::read(pending_path(repo_root)).ok()?;
    serde_json::from_slice(&bytes).ok()
}

/// Remove `<repo_root>/.arc/ai/pending.json` (best-effort; silently ignores errors).
pub fn clear_pending_ai(repo_root: &Path) {
    let _ = std::fs::remove_file(pending_path(repo_root));
}

/// Returns `true` if a pending AI change exists for this repository.
pub fn has_pending_ai(repo_root: &Path) -> bool {
    pending_path(repo_root).exists()
}

