name: GitHub Actions Security Analysis

on:
  push:
    branches:
      - main
      - "run-ci/**"
      - "**/run-ci/**"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.x
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v1.x
        with:
          persona: pedantic
